# Generated by Django 3.1.12 on 2022-04-19 13:15

from django.db import migrations, models
import djongo.models.fields
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', djongo.models.fields.EmbeddedField(model_container=myapp.models.Dokumentasi)),
            ],
        ),
        migrations.CreateModel(
            name='EntryProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop', djongo.models.fields.EmbeddedField(model_container=myapp.models.Proposal)),
            ],
        ),
        migrations.CreateModel(
            name='EntryUm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umum', djongo.models.fields.EmbeddedField(model_container=myapp.models.Pengumuman)),
            ],
        ),
    ]
